// Gemini TTS prebuilt voices. Names are Google's own codenames; the "tag"
// is Google's one-word character description (not an official gender label).
export const VOICES = [
  { name: "Sulafat", tag: "따뜻함" },
  { name: "Achird", tag: "친근함" },
  { name: "Vindemiatrix", tag: "부드러움" },
  { name: "Kore", tag: "단단함" },
  { name: "Leda", tag: "젊고 발랄함" },
  { name: "Autonoe", tag: "밝음" },
  { name: "Callirrhoe", tag: "편안함" },
  { name: "Despina", tag: "매끄러움" },
  { name: "Gacrux", tag: "중후함" },
  { name: "Schedar", tag: "차분하고 고른 톤" },
  { name: "Puck", tag: "경쾌함" },
  { name: "Charon", tag: "설명조" },
  { name: "Fenrir", tag: "흥분됨" },
  { name: "Orus", tag: "단단함" },
  { name: "Aoede", tag: "산뜻함" },
  { name: "Enceladus", tag: "숨소리 섞임" },
  { name: "Iapetus", tag: "또렷함" },
  { name: "Umbriel", tag: "편안함" },
  { name: "Algieba", tag: "매끄러움" },
  { name: "Erinome", tag: "또렷함" },
  { name: "Algenib", tag: "허스키함" },
  { name: "Rasalgethi", tag: "설명조" },
  { name: "Laomedeia", tag: "경쾌함" },
  { name: "Achernar", tag: "부드러움" },
  { name: "Alnilam", tag: "단단함" },
  { name: "Pulcherrima", tag: "적극적임" },
  { name: "Zubenelgenubi", tag: "캐주얼함" },
  { name: "Sadachbia", tag: "생기있음" },
  { name: "Sadaltager", tag: "노련함" },
  { name: "Zephyr", tag: "밝음" },
];

export const STYLE_PRESETS = [
  "담담하게, 차분한 나레이션 톤으로",
  "따뜻하고 다정하게",
  "슬프고 먹먹하게, 울먹이듯",
  "긴장감 있게, 목소리를 낮춰서",
  "속삭이듯 작은 목소리로",
  "밝고 경쾌하게",
  "단호하고 힘있게",
  "천천히, 한 글자씩 또박또박",
];
